language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update
    - git submodule update --recursive --init
install:
    - pip install cython
script: make
virtualenv:
    system_site_packages: true
