language: python
python:
    - "2.7"
sudo: required
before_install:
    - git submodule update --recursive --init
install:
    - pip install cython
script: make
virtualenv:
    system_site_packages: true
